Server:
    RunMode:  debug
    HttpPort: 9090
    ReadTimeout: 60
    WriteTimeout: 60
App:
    ServiceName: gin-template
    DefaultPageSize: 10
    MaxPageSize: 100
    DefaultContextTimeout: 60
    LogSavePath: storage/logs
    LogFileName: app
    LogFileExt: .log
    UploadSavePath: storage/uploads
    UploadServerUrl: http://127.0.0.1:9090/static
    UploadImageMaxSize: 5 # MB
    UploadImageAllowExts:
        - .jpg
        - .jpeg
        - .png
Email:
    Host: smtp.qq.com
    Port: 465
    UserName: xxx@qq.com
    Password: xxxx
    IsSSL: true
    From: xxx@qq.com
    To:
        -  xxx@qq.com
JWT:
    Secret: test123
    Issuer: test-service
    Expire: 7200
Database:
    DBType: mysql
    UserName: root
    Password: 123456
    Host: 127.0.0.1:3306
    DBName: test
    TablePrefix: test_
    Charset: utf8
    ParseTime: True
    MaxIdleConns: 10
    MaxOpenConns: 30

Jaeger:
    Host: 127.0.0.1:4318
